version: "3.8"

services:
  server-mysql:
    image: mysql:8
    container_name: dbmysqlsserver
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=devus
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=dventas
    ports:
      - "3307:3306"
    networks:
      - "net-developers"
    volumes:
      - data-mysql-dbvol:/var/lib/mysql
networks:
  net-developers:       
volumes:
  data-mysql-dbvol: